language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm
services:
  - mysql
before_script:
  - mysql -u root --password="" < assets/database/queueserver.sql
  - composer self-update
  - composer install
script:
  php vendor/codeception/codeception/codecept run