language: php
php:
- 7.1
- 7.2
services:
  - mysql
before_script:
  - mysql -u root --password="" < assets/database/queueserver.sql
  - composer self-update
  - composer install
script:
  php vendor/codeception/codeception/codecept run